package(default_visibility = ["//visibility:public"])

cc_library(
  name = "tuple",
  hdrs = ["tuple.h"]
)

cc_library(
  name = "stop_token",
  hdrs = ["stop_token.h"],
  srcs = ["stop_token.cpp"]
)